name: Create Preload Report
run-name: Build Report for ${{ inputs.ARTIFACT_NAME }} version ${{ inputs.VERSION }} for ${{ inputs.PROJECT }} for ${{ inputs.STORES }}

on:
  workflow_dispatch:
    inputs:
      PROJECT:
        description: 'Project Name'
        required: true
        default: quebec
        type: string
      STORES:
        description: "List of Stores"
        default: '["store21"], ["store22"]'
      VERSION:
        description: 'Version'
        required: true
        default: 1.2.2
        type: string
      ARTIFACT_NAME:
        description: 'Select Artifact'
        type: choice
        default: ALL
        options:
        - ALL
        - trtserver
        - models
        - gaize
        - rrtsp

jobs:
  TRTServer-Report:
    name: TRT Report
    runs-on: ubuntu-latest
    if: ${{ (github.event.inputs.ARTIFACT_NAME == 'trtserver') || (github.event.inputs.ARTIFACT_NAME == 'ALL') }}
    env:
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build report and display summary
        run: |
          ./sample.sh trtserver ${{ inputs.PROJECT }} ${{ inputs.VERSION }} ${{ inputs.STORES[@] }}
      - name: Ready Stores
        run: |
          echo "Ready Stores:"
          cat ./ready_stores.txt
      - name: Failed Stores
        run: |
          echo "Failed Stores:"
          cat ./failed_stores.txt
          echo
          echo "List:"
          ./scripts/preload-artifacts/make-store-list.sh ./failed_stores.txt
      - name: Not Ready Stores
        run: |
          echo "Not Ready Stores:"
          cat ./notready_stores.txt
          echo
          echo "List:"
          ./scripts/preload-artifacts/make-store-list.sh ./notready_stores.txt
