name: Create Preload Report
run-name: Build Report for ${{ inputs.ARTIFACT_NAME }} version ${{ inputs.VERSION }} for ${{ inputs.PROJECT }} for ${{ inputs.STORES }}

on:
  workflow_dispatch:
    inputs:
      PROJECT:
        description: 'Project Name'
        required: true
        default: quebec
        type: string
      STORES:
        description: "List of Stores"
        default: '["store21", "store22"]'
      CANARY_STORES:
         type: boolean
         default: false
         description: 'Generate report for canary stores'
      VERSION:
        description: 'Version'
        required: true
        default: 1.2.2
        type: string
      ARTIFACT_NAME:
        description: 'Select Artifact'
        type: choice
        default: ALL
        options:
        - ALL
        - trtserver
        - models
        - gaize
        - rrtsp

jobs:
  TRTServer-Report:
    name: TRT Report
    runs-on: ubuntu-latest
    if: ${{ (github.event.inputs.ARTIFACT_NAME == 'trtserver') || (github.event.inputs.ARTIFACT_NAME == 'ALL') }}
    env:
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
      CANARY_STORE: 'store17 store21 store23 store24 store25 store26 store27 store53 store58 store62 store70 store80 store84 store85 store90 store121 store408'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build report and display summary
        run: |
           chmod +x sample.sh
           if [ "$CANARY_STORES" == "true" ]; then
             ./sample.sh trtserver ${{ inputs.PROJECT }} ${{ inputs.VERSION }} "${{ inputs.STORES }}" $CANARY_STORE
           else
             ./sample.sh trtserver ${{ inputs.PROJECT }} ${{ inputs.VERSION }} "${{ inputs.STORES }}"
           fi
