name: Canary Stores Report

on:
  workflow_dispatch:
    inputs:
      run-canary-report:
        description: 'Run Canary Report'
        default: false
      canary-stores:
        description: 'List of Canary Stores'
        default: 'store17,store21,store23,store24,store25,store26,store27,store53,store58,store62,store70,store80,store84,store85,store90,store121,store408'

jobs:
  canary-report-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        canary-store:
          - store17
          - store21
          - store23
          - store24
          - store25
          - store26
          - store27
          - store53
          - store58
          - store62
          - store70
          - store80
          - store84
          - store85
          - store90
          - store121
          - store408

    inputs:
      run-canary-report:
        description: 'Run Canary Report'
        default: false
      canary-stores:
        description: 'List of Canary Stores'
        default: ''

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Canary Report
        if: ${{ github.event.inputs.run-canary-report == 'true' }}
        run: |
          # Iterate over selected canary stores from the matrix
          for store in "${{ matrix.canary-store }}"; do
            echo "Running report for store: $store"
            # Add your report generation command for each store here
            # For example, echo "Generating report for $store"
          done
